### ISSUE TITLE
spawn primitive does not work

### ISSUE THREAD

**Issue by klag** [jolie/jolie#10]
This code is getting stuck when executing the spawn

include "console.iol"

main {	
	vec[0]="hello0";
	vec[1]="hello1";
	vec[2]="hello2";
	println@Console("begin")();
	spawn( i over #vec ) in result {			
			println@Console( vec[ i ] )()
	};
	println@Console("end")()

}

**Comment by fmontesi** [comment]
Probably due to my latest changes to the threading code. This means that neither the test suite nor the website test spawn, since that's what I use for testing changes. 

I'll have a look. Meanwhile, can you create a simple test in the test suite (inside of primitives) so that we catch this in the future?

**Comment by fmontesi** [comment]
Actually nevermind, I can create one easily already from your example by using Math instead of Console (for testing result).

**Comment by fmontesi** [comment]
Should work now.
