### ISSUE TITLE
Incongruences in fault catching

### ISSUE THREAD

**Issue by lanese** [jolie/jolie#100]
I have done, together with @thesave  some experiments with system faults (i.e., not from throw) with strange results:

- fault IOException is caught by handler for IOException, but not by default
- fault CorrelationError is caught by handler for CorrelationError, and by default
- fault UnsupportedCommMediumException is caught by IOException, but only if the scope is not main
- we have not been able to catch in any way a division by zero 

In attachment the code for CorrelationError. The one for IOException is simply an invocation to a 
non existing server. The code for UnsupportedCommMediumException will be provided by @thesave. 

This beahvior seems quite random. Is there a (simple) general rule? If not, I think it would be good to decide on one (e.g., each fault caught by its own name and by default, in any scope) and make it coherent.
[correlation.zip](https://github.com/jolie/jolie/files/575830/correlation.zip)

**Comment by thesave** [comment]
I tried to compile a comprehensive example:

with scopes

- BLOCK 1 `UnsupportedCommMediumException` is caught by `IOException`;
- BLOCK 2 `UnsupportedCommMediumException` is caught by `default` as `IOException`;
- BLOCK 3 `ConnectionException` is caught by `IOException`;
- BLOCK 4 `ConnectionException` is caught by `default` as `IOException`.

without scopes

- BLOCK 5 `UnsupportedCommMediumException` is caught by `IOException`;
- BLOCK 6 (comment BLOCK 5) `ConnectionException` is caught by `IOException`;
- BLOCK 7 (comment BLOCK 5-6) `UnsupportedCommMediumException` is missed by `default`;
- BLOCK 8 (comment BLOCK 5-7) `ConnectionException` is missed by `default`;

[fault_tests.ol.txt](https://github.com/jolie/jolie/files/576057/fault_tests.ol.txt) (remove .txt extension)

**Comment by lanese** [comment]
I can add that TypeMismatch is caught by TypeMismatch but not by default. Code example in attachment.
[interface.iol.txt](https://github.com/jolie/jolie/files/578715/interface.iol.txt)
[sender.ol.txt](https://github.com/jolie/jolie/files/578718/sender.ol.txt)

**Comment by fmontesi** [comment]
@thesave Have you tried debugging `ExecutionThread.Scope.getFaultHandler` with @lanese 's last example?

**Comment by thesave** [comment]
I didn't. Next week I'll try to work on it.

**Comment by fmontesi** [comment]
Any news on this?

**Comment by thesave** [comment]
Shamefully, I found no time to track that bug :(
Hope to find some in the next months.

**Comment by thesave** [comment]
Hi, I had some time to look at the bug. The problem is [here](https://github.com/jolie/jolie/blob/master/jolie/src/jolie/SessionThread.java#L206) (commented code) where the installation of two default handlers, one for TypeMismatch and one for IOException, (correctly) prevented the triggering of the `default` handler.

Since the two default handlers just printed a warning on screen, in this [branch](https://github.com/jolie/jolie/tree/casting_exceptions), I propose to remove those handlers and use an enhanced version of the [logUnhandeledFault](https://github.com/jolie/jolie/commit/34d1c15c448d0c5aff9645b6748f7a6fee0ffa53#diff-c8bda5254444a396aa21ac36f4f09b73L665) to log fault, message, and stack trace.

Could it be a viable solution?

The branch also introduces exceptions on casting (contrarily, now if we write `int( "hello" )` we get `0`) and it  raises a catchable "ArithmeticException" for the division by zero (also a problem reported above).

**Comment by fmontesi** [comment]
@thesave Can you separate this fix from the casting work? We should discuss the two issues separately. If the casting work is ready for review, can you open a (separate) pull request for that?

**Comment by fmontesi** [comment]
Should be solved now.
