### ISSUE TITLE
Program preemptively exits before execution of internal service

### ISSUE THREAD

**Issue by kicito** [jolie/jolie#199]
Hi all,

Jolie learner here. This might be an anti-pattern of writing programs in Jolie. I would like to have an easy way to log my variable in my program so I create an internal service as following

```
include "console.iol"
include "json_utils.iol"

type anyType: any{?}

interface LoggerIface{
    RequestResponse: log(anyType)(anyType)
}

service Logger{
  Interfaces: LoggerIface
  main{
    [log(req)(res)]{
      getJsonString@JsonUtils( req )( res )
      println@Console(res)()
    }
  }
}

main{
  log@Logger( { .a="test-a", .a.d = "test-b"})(res)
}
```

**Expected:** console output {"a":{"$":"test-a","d":"test-b"}}
**Actual:** nothing

This behavior happens either with `OneWay` or `RequestResponse` without further usage of response returned from service (as above). I understand that this is due to the main scope has nothing else to execute next, so it exits. But since `RequestResponse` is synchronous so the sender `main` should've wait for service `Logger` to finish it's execution.

**Comment by thesave** [comment]
Welcome @kicito :)

You are close to the solution.
The "problem" is how you define the behaviour linked to the invocation of the `log` operation into the Logger service:

`[ log( req )( res ){ /* do nothing before response */ } ]{ /* do something after response */ }`

Concretely, you get the request, you do nothing, you send back the response and then you execute the code to print out the value. 

Of course, this is a legitimate code. However, by doing that, you introduce a race. 

What happens at runtime is that the main program, i.e., the one your Logger service depends on, calls the Logger, it receives the response (empty) and then proceeds to terminate, since it terminated all its code (there are no other statements in the main block of the invoker). Meanwhile, the dependent service (the logger) is going on executing some code (the post-response code you defined), but it is caught mid-execution by the termination of the parent service.

You can observe this behaviour in different ways. One is using the `--trace` parameter when launching your service (e.g., `jolie --trace myService.ol`), which allows you to see all the message exchanges. Another, related to races, is to use a `sleep@Time()()` to wait some seconds (try with 500 (ms), it should be enough) for the code of the internal service to terminate.

If you *do not* want the race to be there in the first place, just move your code into the pre-response block, so that it is guaranteed to execute before the invoker goes on with the next instruction.

Related to your intent with this service, I suggest using the `valueToPrettyString` [1] operation of the StringUtils library, which, given a Jolie variable, returns to you a nicely formatted string representation (with nesting and associated types).

[1] https://jolielang.gitbook.io/docs/standard-library-api/string_utils#valueToPrettyString

**Comment by kicito** [comment]
I see it now. After move code block in to square blanket it is working as expected. Thank you for the clarification.
