### ISSUE TITLE
JolieDoc and code comments

### ISSUE THREAD

**Issue by mwallnoefer** [jolie/jolie#20]
Our generated API documentation (http://docs.jolie-lang.org) loses all (helpful) comments written in the various headers. Not sure if we can fix it, since they pass the Jolie parser which correctly ignores comments before being converted into the doc format. Did I get this right?

**Comment by fmontesi** [comment]
We could do it like in Doxygen and add something for inline documentation comments:

type t:void {
  /// the number x
 .x : int 
}

Actually our syntax right now is a bit ugly: /**! */

I suggest we support also (I say also because I don't want to break backwards compatibility):

/** */ as in javadoc
/// for inline comments

Also, sometimes it is useful to write a comment for something *after* the something, e.g.

type t:void {
  .x : int //< the number x
}

That //< tells the parser that the comment is meant for the previous grammar production.

For these "backwards" comments, we could use:

/*< */ for blocks
//< for inline comments

or just follow doxygen and Qt:

/**< */
///<

**Comment by fmontesi** [comment]
@mwallnoefer Any new thoughts about this issue?

**Comment by mwallnoefer** [comment]
Yeah, I have noticed that the /**! */ comments get considered by our documentation tool. The plan to support additional syntaxes as the javadoc (/** */) one is not bad.

Maybe we should start to progressively migrate our plain comments to documentation ones in the various header files. This is a huge task and cannot be done in one shot but step-by-step.

**Comment by mawolf** [comment]
I have started working on this. Progress can be seen in https://github.com/mawolf/jolie/tree/new-doc

**Comment by fmontesi** [comment]
Cool, looking forward to it. :-)

**Comment by mawolf** [comment]
I started implementing the doxygen and Qt version of backward comments, however, when converting some of the comments in the include files I quickly felt awkward typing ///< instead of //<.

What do you think? What version should be supported (same for /*< */ for blocks)?

I was also thinking about implementing them both, but I think that it would be a bad idea to support many different ways of doing the same.

**Comment by mwallnoefer** [comment]
@mawolf Is this subproject finished? Did we decide some syntax to use?

**Comment by mwallnoefer** [comment]
Also this seems to have been addressed in the meantime.
