### ISSUE TITLE
Potential lack of clarity when parsing types

### ISSUE THREAD

**Issue by klag** [jolie/jolie#219]
This type does not generate any error by the parser

```
type Type: void {
    .field1* string somethingelse
    .field2: int
}
```

**Comment by fmontesi** [comment]
You're mixing legacy and new syntax. When you don't specify the native type it's void, and . are optional.

So that might be interpreted as:
```jolie
type Type:void {
  field1*:void
  string:void
  somethingelse:void
  field2:int
}
```

Could you check that's the case?

**Comment by klag** [comment]
If it is the case, I think it is important to introduce \n as a token for differentiating the fields because it is too easy to write bad code in interface which can be discovered only at runtime.

**Comment by fmontesi** [comment]
Mmh, that would mess up with quite a lot of code, e.g.,

```jolie
type point { x:int y:int }
```

An alternative would be to simply forbid having a void node with no subnodes. Does it even make sense? For example, why would one ever write something like the following?

```jolie
type t { x:void }
```

I don't like this alternative though because I see nothing wrong with it (yet) from a theoretical point of view.

I think that the right solution is just to print a warning whenever something like this is written. What do you think?

**Comment by klag** [comment]
I am a little bit conservative from this point of view.
I think the syntax must clear and not ambiguous.
I do not like the idea to have a warning because a warning means you are programming  in a not proper way, so why are we allowing to program in a no proper way?

I do not like the idea to hide the "void", I think it is better for people to know that in the root there is a place for a value which is set as void. It is an immediate and fundamental information.

I would like to go back to the previous syntax which was more robust than this one.

**Comment by fmontesi** [comment]
Mmh, we need to weight all pros and cons then, and that's a large discussion, let's take it at a meeting.

I'm switching this to a discussion in the meantime.

**Comment by fmontesi** [comment]
Resolved. The . prefix for types now requires a new line and is considered legacy.
