### ISSUE TITLE
Behaviour of double * int different from int * double

### ISSUE THREAD

**Issue by szingaro** [jolie/jolie#232]
## Reproduce

Consider the following code (actual output in the comments):

```jolie
include "console.iol"

main
{
  a = 0.1 * 1000
  b = 1000 * 0.1
  println@Console( a == b )() # false
  c = double( 1000 ) * 0.1
  println@Console( a == c )() # true
}
```

## Question

Is this **asymmetric behaviour** wanted? 
Not sure this should be a bug, I was just wondering why this choice.

## Context

- MacOSX 10.15.5
- Jolie interpreter 1.9.0
- OpenJDK Runtime Environment (build 13+33)

**Comment by kicito** [comment]
This bug is occur from the basic number operation is only checks type for left value of the operation only perform type check in left hand side. 
https://github.com/jolie/jolie/blob/490815e45c4772c6122ccced464732250cc506dd/jolie/src/main/java/jolie/runtime/Value.java#L950-L965
Thus,  in the example above, assignment process to b is translated into b = 1000 * 0 .

I created a pull request for this issue in #233
