### ISSUE TITLE
API refactoring regarding boolean parameters

### ISSUE THREAD

**Issue by mwallnoefer** [jolie/jolie#24]
Before releasing a new major release, we should transform all int parameters which are intended as boolean. I know that such a change breaks compatibility, but let us discuss it here. For instance in the Database service we have:

type ConnectionInfo:void { 
    .port?:int
    .toUpperCase?:bool
    .username:string
    .host:string
    .checkConnection?:int   < should become bool
    .toLowerCase?:bool
    .driver:string
    .attributes?:string
    .password:string
    .database:string
}

**Comment by fmontesi** [comment]
I agree, but this will have huge implications. I could open a dedicated branch for this, but I think that the next major release is too soon.

I'd feel much more at ease if we implemented a static type checker first. That way one could check whether old services need updating. Complete static type checking in Jolie is difficult due to [dynamic look-up](http://docs.jolie-lang.org/#!documentation/basics/data_structures.html#dynamic-look-up), but we can probably handle almost all other cases (ignoring checking array sizes, that's undecidable, we can only check that something is an array or not).

Any other ideas for simpler tools that would help people in the transition?

If we don't provide tools, this could have to wait basically until Jolie 2.0... which sucks, to be honest. :-)

**Comment by klag** [comment]
I would like to use this issue for starting a discussion about service versioning. We will encounter the same problem in the future and I cannot imagine that every time we will have to update all the installed code. Thus, we have to deal with service versioning in some way. In my opinion, old versions must remain available. Maybe we could exploit JPM for managing service versioning?

**Comment by fmontesi** [comment]
I would open a separate issue because

**Comment by fmontesi** [comment]
@klag Can you open a separate issue for discussing it? Versioning a-la' microservices can already be done with redirections and collections, but here we're talking about packages and libraries so we should discuss that in details and probably get some inspiration from the new java specs for package versioning, to see if we can reuse some concepts (in the forthcoming Java 9).

**Comment by mwallnoefer** [comment]
Okay, some kind of versioning has been introduced so we may close also this one.
