### ISSUE TITLE
deep copy does not erase the assigned values

### ISSUE THREAD

**Issue by klag** [jolie/jolie#273]
Let us consider this code:
`
c.a = 10
c << 11 {}
valueToPrettyString@StringUtils( c )( s )
println@Console( s )()
`
this is the output:
`
Value = 11 : int
        .a[0] = 10 : int
`

The deep copy adds a tree to the current tree. But I think it is misleading. We should have a specific operator for adding a tree to another. 

for example: 
a << b, it undefs a and deep copy b into a
a <<< b, it acts like the current deep copy operator

**Comment by mwallnoefer** [comment]
I share your opinion @klag about performing a redefinition in the case of the tree assignment operator (`<<`). But the introduction of `<<<` seems a bit overkill to me, we shouldn't be complicating the language to much.
Existing code could simply be fixed by reordering: first perform the tree assignment (`<<`) and then do plain value assignments on behalf of `=`.

**Comment by fmontesi** [comment]
Apparently it works as documented: https://jolielang.gitbook.io/docs/language-tools-and-standard-library/basics/data_structures#less-than-less-than-copying-an-entire-tree-structure

But I'm not sure it works as I originally intended.. :-)
I need to think about what would make more sense.

Copying without erasing seems more primitive than copy after erasing, since one can always `undef(c); c << 11 {}`.

**Comment by klag** [comment]
I think we need both the possibilities. At the beginning deep copy was used rarely, but now is widely used because of the new syntax of inline trees.

Intuitively, << has the same meaning of = for scalars and the first expectation is that the variable is cleaned and filled. Thus, I propose to change the semantics of << clearing the assigned variable before the assignment.

Then, we need also the possibility to merge two trees. I don't know if an operator (<<<) is the right choice. Maybe TQuery will solve this problem.

**Comment by mwallnoefer** [comment]
Any news?

**Comment by fmontesi** [comment]
The more @mperessotti, @xpicox, and I work on the theory of Jolie types and trees, the more I tend to agree that there should exists an operator that creates a clean copy. "Merging" two data trees should instead be a binary operator between two values/expressions, which once we introduce copyless messaging could even be a library in the beginning.

I don't know how much existing code would break by redefining the semantics of `<<`. Possible options:
- Ignore the problem, just redefine `x << expr` to "set x to the value of expr". Pro: works now. Cons: legacy code now behaves differently; `<<` recalls "adding" to a collection/stream (e.g., in C++) rather than `setting`/`assigning`.
- Add a new operator like `x := expr` (or some other similar syntax) that sets x to the value of expr and deprecate `<<`. Pros: it's clear it is an assignment; old code keeps working as before. Con: language becomes more complicate.

@xpicox, @mperessotti, @thesave, @klag, @mwallnoefer, thoughts are very welcome.

**Comment by thesave** [comment]
I recall spending a day with Stefano Pio Zingaro, while working on Tquery, on the various dimensions you can play with to define equality and merging — they are used in the semantics of some operators — for Jolie (IIRC 3D: values, arrays, and trees, where, e.g., you might want to have symmetry or not, etc.) 😄
That was also one of the motivations I wanted to explore macros for Jolie, but, now that we have functions, a library would probably fit the bill (from an ergonomics point of view).
What if we followed the same idea with the := operator to avoid complicating the language? Could that approach would work or does the operator need to be defined as primitive?

**Comment by fmontesi** [comment]
There are indeed many dimensions, but the trick with the `Vector` type might allow us to focus on trees. :)
Sure, to encode `x := expr` you could just invoke the identity request-response `id@library( expr )( x )`, or simply write `undef( p ); p << expr`. Similar stuff could be done for deep copy `<<`.

What smells to me here is that in inline trees, we write stuff like this:

```
x << {
  y << { z = 3 }
}
```

but what we actually mean is:
```
x := {
  y := { z = 3 }
}
```

Having `<<` in inline trees allows us to do something weird potentially, which I would actually forbid, i.e.,

```
x << {
  y << { z = 3 }
  y << { w = 4 }
}
```

This makes sense with `<<`. We would get that x is `{ y << { z = 3, w = 4 } }`. But is it sane to do these kind of things? I don't think so (at least now... opinions?). If we forbid to use a key multiple times in an inline tree, then what we mean is `:=` (for which forbidding to use the key multiple times makes intuitive sense, since using `:=` on the same path twice makes the first assignment redundant).

So at the end of the day, the question is: what's more "primitive"? :)

Your way of defining operators would definitely yield something interesting here, we could just make `:=` a library operator, but unfortunately the performance of our calls is still not on par with native operators even if we consider `&`, so it'd require quite a bit of work.

**Comment by fmontesi** [comment]
FYI, this has important connections to copyless passing (passing by reference), so we should probably solve them in the same pull request:
- The current `<<` is not so easy to implement efficiently. Instead if it redefined, then `x << &p` could just set `x` to the tree returned by `&p` (this is "instantaneous").
- With copyless passing, it's possible to implement an efficient operation like `merge@values( { fst << &x, snd << &y } )( result )`. Without copyless passing, it's not.

**Comment by fmontesi** [comment]
Dear all,
I've opened the GitHub discussions feature to have open-ended discussions like these. Let's try it out to see if we like it. :)
For this issue, please continue in https://github.com/jolie/jolie/discussions/419
