### ISSUE TITLE
generateDocumentation.ol does not work

### ISSUE THREAD

**Issue by fmontesi** [jolie/jolie#3]
If I try to run it on the website server to re-generate the docs, it prints:

INFO: [generateDocumentation.ol] Output message TypeMismatch (getFiles@Self): Invalid native type for node #Message: expected STRING, found void

Apparently we're doing something wrong with the paths. Saverio, can you look into this?

**Comment by thesave** [comment]
Looking into it

**Comment by thesave** [comment]
It appears to be working with the command
`jolie build_jsl.ol ../documentation/jsl $JOLIE_HOME/include/`

However there was a bug in the creation of subpaths.
I fixed it and better documented the service and its output.

I think it makes sense to have that script in documentation rather than the `jolie` repo. 
Right now I just copied the script from the `jolie` repo to the `website` repo inside folder `docs/site_builder`, renaming it build_jsl.ol. 
I also added in the folder a bash script to launch the compilation of the documentation and to build the JSL library.

Please check the commit message for the `website` repo before pulling the last update.

**Comment by fmontesi** [comment]
OK, works now. :+1:
