### ISSUE TITLE
When a service is embedded by a parent in another path, File Service does not work

### ISSUE THREAD

**Issue by klag** [jolie/jolie#33]
If you embed a service in a parent which is run in a different path of the embedder, the FileService always performs its operation starting from the path of the parent.

This is a problem because when you program a microservice you want to be responsible of the file system managed by that microservice, that is usually considered as all the folders and files contained in the microservice project folder.

**Comment by fmontesi** [comment]
Yes, I've always wondered about this. I have never implemented this because it will break backwards compatibility, so if we do it, it should be a major release with a big warning sign saying that all embedded services may break.

**Comment by klag** [comment]
I think we should seriously think to a consistent way of service versioning which should work both for jolie services and java services.

**Comment by fmontesi** [comment]
Yes. For now, the only way to handle this kind of situations is using 3rd-party containers or virtualisers (e.g., Docker), where you deploy services using different versions of Jolie (this methodology is the current standard in microservices afaik). Anyway, let's continue the discussion on versioning on the ML since it is bigger than this particular issue on the file service.

**Comment by klag** [comment]
I think the current version of coreJavaService should be versioned as the 1.0.0. All the JavaService inside should take this version.

Then, I suggest to create a different Javaservice for each Javaservice contained in coreJavaService. The new Javaservices will be natively verisioned in some way.

interface names and type names should be changed in order to deal with versioning.
include primitive should deal with versions, ex:

include "my_interface.iol" 1.0.3 (version number could be in the file name)
when version is omitted it takes 1.0.0

names should be addressed to, in particular interface and type names.
ex.
 interface MyInterface_103 {
}

In this way all the old services should continue to work and the new ones can be used.
it is just for starting a discussion.

**Comment by fmontesi** [comment]
@klag 

What's the behaviour we should be looking for, exactly? This is what I'd expect:
1 - When a service is launched by command line, the working path for File should be the directory the command was launched from.
2 - When a service is embedded, the working path of its File should be the directory of the embedded service.

But it seems inconsistent: in theory, it should make no difference whether a service is launched from the command line or is embedded.

The only safe way to code this is to use getServiceDirectory@File from the service itself (our current practice). This may not work very well with JAPs though.

I'm wondering if we should be seeking to have options for embedding instead of finding a one-size-fits-all solution here. For example, sometimes we may wish to containerise an embedded service such that it can access only files in a certain directory, etc.

```
embedded {
Jolie[workingPath="/my/path"]: "mysrv.ol" in Srv
}
```

**Comment by klag** [comment]
Yes, it could be the right solution!

**Comment by mwallnoefer** [comment]
Also this could have been fixed in the meantime, since the path handling was changed. Please double-check!

**Comment by mwallnoefer** [comment]
Closing it for now.
