### ISSUE TITLE
Timeouts for Solicit-Responses (Request-Response invocations)

### ISSUE THREAD

**Issue by fmontesi** [jolie/jolie#9]
Right now, a solicit-response invocation, for example

getUsers@Srv()( users )

can wait for a long time, and be interrupted by an IOException only when the underlying communication channel goes into a low-level timeout (e.g., a socket connection timeout).

It would be much nicer to be able to specify timeouts at the language level (note that this is not a problem for inputs since we can use input choices, with a particular input representing a timeout).

An option would be to have it as a configuration parameter, for example per operation (here I use the same .osc syntax as for http):

outputPort Srv {
Protocol: sodep { .osc.getUsers.timeout = 500 /\* msecs */ }
}

I discussed this a bit with @klag and @thesave , they may have something to add (and I may have forgotten something ;-) ).

In case somebody is interested in working on this, a possible way is to change AbstractCommChannel.recvResponseFor to inspect the timeout parameter and use its value for waiting on the monitor on which the invoker waits for the response message. Feel free to ask here for more details.

**Comment by klag** [comment]
I tried to insert a timeout into the monitor.wait() method where
If it is raised a FaultException called "SolicitResponseTimeoutFault" is returned to the SolicitResponse process.

It works fine but the interpreter still waits for the response from the sender before processing the SR.
The final result is that, otherwise the timeout at the level of the monitor is raised, the SR process is blocked until the response is received.

In details:
This is the JOLIE process which I used for test:
scope( try ) {
		install( SolicitResponseTimeoutFault => println@Console("SR fault")() );
		test@Test()()
};
println@Console("done")()

the server just replies after 10secs (that is after the timeout on the wait is raised)

test@Test is the SR which should raise the timeout.

Inside recvResponseFor the monitor.wait is set to wait until 3000 msecs then SolicitResponseTimeoutFault is returned to the SR Process which uses that method (test@Test).

I checked that the recvResponseFor method correctly returns the FaultException to the SolicitResponseProcess and thorws the FaultException.

but statement println@Console("SR fault")()  is executed only when the real response from the server is received.

Summarizing:
The SolicitResponseTimeoutFault is correcty raised by the SR process, but the SR process is till blocked until the real response is sent by the server.

Maybe there is another lock at the level of the process which waits for the message reception at the level of the channel? Any suggestion?

**Comment by fmontesi** [comment]
@klag Where can I see your code? Have you forked master (or java8)?

**Comment by klag** [comment]
I did not create any branch because I was just making some test in my local machine.
The code is very simple, in AbstractCommChannel.java I just replaced the following code at line 83.

                      synchronized( monitor ) {
			      if ( monitor.response == null ) {
					try {						
						monitor.wait(  3000 );						
					} catch( InterruptedException e ) {
						Interpreter.getInstance().logSevere( e );
					}
				}
				if ( monitor.response == null ) {
					// timeout raised
					response = new CommMessage(
						request.id(),
						request.operationName(),
						request.resourcePath(),
						null,
						new FaultException("SolicitResponseTimeoutFault")
					);					
							
				} else {
				    response = monitor.response;
				}
			}

**Comment by fmontesi** [comment]
Confirmed.

It's release() called on the channel from SolicitResponseProcess that does not terminate. I'll investigate this asap.

**Comment by mawolf** [comment]
Hi @fmontesi 
Did you come closer a solution, or can I have a look?

BTW: Is it on purpose that you cannot declare a timeout for embedded services in your suggestion?

**Comment by fmontesi** [comment]
Feel free to have a look, this got lost somehow.

@klag: @mawolf is right, we did not talk about what to do with embedded services, which do not have a protocol. Where would we specify the timeout then?

**Comment by fmontesi** [comment]
This is now fixed in master.
An SR timeout throws the Timeout fault. The response timeout is configurable from command line (parameter --responseTimeout).
